### ISSUE TITLE
job HCL at https://www.nomadproject.io/docs/drivers/podman doesn't work

### ISSUE THREAD

**Issue by inflatador** [hashicorp/nomad-driver-podman#79] opened 2020-12-31 17:08 UTC
running the job at https://www.nomadproject.io/docs/drivers/podman , I get the following output
```
#  nomad job status example
ID            = example
Name          = example
Submit Date   = 2020-12-31T11:01:12-06:00
Type          = service
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = pending
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
cache       0       0         0        7       1         0

Future Rescheduling Attempts
Task Group  Eval ID   Eval Time
cache       b85161ee  8s from now

Latest Deployment
ID          = 98f44b15
Status      = running
Description = Deployment is running

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
cache       1        2       0        2          2020-12-31T11:11:12-06:00

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
31a8f33b  4072e015  cache       3        run      failed    52s ago    48s ago
 
#nomad alloc status 9302e0ec
ID                   = 9302e0ec-787d-81a8-ee8e-34a9a837d8dd
Eval ID              = 0526f33d
Name                 = example.cache[0]
Node ID              = 4072e015
Node Name            = dc1
Job ID               = example
Job Version          = 5
Client Status        = failed
Client Description   = Failed tasks
Desired Status       = stop
Desired Description  = alloc was rescheduled because it failed
Created              = 1m29s ago
Modified             = 6s ago
Deployment ID        = fc5bf8f0
Deployment Health    = unhealthy
Replacement Alloc ID = 31e7dd56

Task "redis" is "dead"
Task Resources
CPU        Memory       Disk     Addresses
0/500 MHz  0 B/256 MiB  300 MiB  db: 172.19.64.3:26028

Task Events:
Started At     = 2020-12-31T17:04:15Z
Finished At    = 2020-12-31T17:04:50Z
Total Restarts = 1
Last Restart   = 2020-12-31T11:04:21-06:00

Recent Events:
Time                       Type             Description
2020-12-31T11:04:52-06:00  Killing          Sent interrupt. Waiting 5s before force killing
2020-12-31T11:04:51-06:00  Alloc Unhealthy  Unhealthy because of failed task
2020-12-31T11:04:51-06:00  Killing          Sent interrupt. Waiting 5s before force killing
2020-12-31T11:04:50-06:00  Not Restarting   Error was unrecoverable
2020-12-31T11:04:50-06:00  Driver Failure   rpc error: code = Unknown desc = failed to start task, could not inspect container : unexpected EOF
2020-12-31T11:04:21-06:00  Restarting       Task restarting in 18.502085747s
2020-12-31T11:04:21-06:00  Terminated       Exit Code: 1
2020-12-31T11:04:15-06:00  Started          Task started by client
2020-12-31T11:04:07-06:00  Driver           Image downloaded: Storing signatures
2020-12-31T11:03:58-06:00  Driver           Downloading image
```
OS: CentOS Stream release 8
nomad -version: Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)
podman: version 2.0.5
nomad-driver-podman version: nomad-driver-podman_0.2.0_linux_amd64

**Comment by jrasell** [comment] 2021-05-03 14:06
Hi @inflatador I tested the current job which resides on the main branch of the Nomad documentation (pending release soon) and found the example job worked OK. Is this still a problem you're encountering?

**Comment by jrasell** [comment] 2021-06-17 08:45
Hi @inflatador, I am going to close this issue as I have been unable to reproduce and we have not received a response. If you are still having the problem you described, please feel free to reopen this issue.

**Closed by jrasell** 2021-06-17 08:45 UTC
