### ISSUE TITLE
Mismatch between API call and nomad UI

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/nomad-driver-podman#117] opened 2021-05-29 15:28 UTC
API says podman is `rootless: true`

<img width="1440" alt="Screenshot 2021-05-29 at 8 56 07 PM" src="https://user-images.githubusercontent.com/19410501/120075806-61ae5180-c0c0-11eb-9a7e-4703089df58a.png">

![image](https://user-images.githubusercontent.com/19410501/120076256-3f1d3800-c0c2-11eb-9e47-42d253669df1.png)

Nomad Ui says `rootless: false`

<img width="1156" alt="Screenshot 2021-05-29 at 8 51 31 PM" src="https://user-images.githubusercontent.com/19410501/120075810-6541d880-c0c0-11eb-92be-a0b03f8b128a.png">

There is only one socket for non-root user. There is NO socket for root.

The version of `nomad-driver-podman` is 0.2.0 and of `nomad` is 1.0.4

---

On an alternate bug, I am getting `dial unix /run/podman/podman.sock: connect: no such file or directory"` when no socket is provided.
The expected thing is to scan in BOTH `/run/podman/podman.socket` and `/run/user/<id>/podman/podman.sock`. But looks like it is only checking the first one and throwing error.

Here is my config.

```
plugin "nomad-driver-podman" {
    config {
        volumes {
            enabled = true
            selinuxlabel = "z"
        }
        recover_stopped = true
    }
}
```

**Comment by towe75** [comment] 2021-05-29 17:51
Hi @blmhemu . The API / rootless problem is very likely a duplicate of #92. Maybe you want to try a build from main branch?

Regarding the socket path: yeah, we could check for uid!=0 and simply search for the user socket. Thank you for the hint. I will keep the issue open.

**Comment by blmhemu** [comment] 2021-05-30 03:11
Thanks for the quick reply @towe75
I think the rootless bug is fixed in master and can be marked resolved.

> Regarding the socket path: yeah, we could check for uid!=0 and simply search for the user socket. Thank you for the hint. I will keep the issue open.

Actually, we are doing that but the problem is that we are checking `os.getuid` which seems to be getting the uid of the user which is running this driver / program (in my case the owner of the binary is root). So it is only searching for rooted podman.sock

One solution can be along with uid check, we should check if podman.sock exists. And if both fails, we can iterate over all /run/user/<id>/podman to find any podman.sock and set it as default.

![image](https://user-images.githubusercontent.com/19410501/120090630-a74f3680-c121-11eb-8427-62074f4fc393.png)

**Comment by towe75** [comment] 2021-06-02 18:50
> One solution can be along with uid check, we should check if podman.sock exists. And if both fails, we can iterate over all /run/user//podman to find any podman.sock and set it as default.

A nomad client can already be configure to use a specific socket if the uid's of nomad and podman are different.  I don't like the idea of rolling the dice here. This can end up in weird situations of root is running nomad and a arbitrary user is logged in/not-logged-in while restarting nomad. 

I'm also thinking about a map of symbolic names to sockets paths in the driver config. This way each task could point to a different nomad user (e.g. root, tennant1, tennant2)

Regarding your 500 problem: I suggest to raise the podman.service loglevel to info or debug like so: 

    Environment=LOGGING="--log-level=debug"

Then, restart the podman service and run your job. Check your journal, maybe you spot something.

**Comment by blmhemu** [comment] 2021-06-05 15:20
The error is as follows:

```
2021-06-05T20:48:53.882+0530 [ERROR] client.rpc: error performing RPC to server: error="RPC Error:: 400,ACL support disabled" rpc=ACL.ResolveToken server=xx.xx.xx.xx:4647
2021-06-05T20:48:53.883+0530 [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="RPC Error:: 400,ACL support disabled" rpc=ACL.ResolveToken server=xx.xx.xx.xx:4647
```

**Comment by towe75** [comment] 2021-06-12 11:28
@blmhemu  this seems to be rather some ACL issue between your nomad agents, unrelated to podman. Also this issue starts to become confusing because  you started it with two problems where one is resolved in main branch and the other is basically a matter of correct configuration. 

I can not correlate your latest comment to one of these former problems and also not to the "500" that you got with the redis job.

**Comment by blmhemu** [comment] 2023-04-04 03:55
Hey ! I am sorry, the setup is nuked and am no longer using podman 😞

**Closed** 2023-11-25 03:21 UTC
Labels: stage/waiting-reply, stage/needs-investigation
