### ISSUE TITLE
Run containers from oci-archive and non standard image sources

### ISSUE THREAD

**Issue by towe75** [hashicorp/nomad-driver-podman#69] opened 2020-11-06 20:13 UTC
It would be useful to run containers from images in oci-archive format.
We fixed this issue for varlink api in #67 

But switching to podman api v2 introduces the same problem. This is related to https://github.com/containers/podman/issues/6744

**Comment by onlyjob** [comment] 2021-01-09 12:06
Looks like 0.2.0 was actually released with this regression... :(

CC: @drewbailey, @krishicks

**Comment by towe75** [comment] 2021-01-09 19:55
@onlyjob : it was a misleading information in the changelog,  #67 was fixed right before 0.2.0 release. 
I knew that it would still be broken with http API - hence this ticket. I will handle it soon and this time it's covered with a unit test ;-)

**Comment by onlyjob** [comment] 2021-01-10 06:39
I've backported fix to 0.1.0 and it works with Varlink. However yesterday I tried 0.2.0 and could not start any of my images...

Thank you for your care and attention for driver-podman.

**Comment by towe75** [comment] 2021-01-10 13:02
We're blocked by https://github.com/containers/podman/issues/8927

**Comment by towe75** [comment] 2021-01-15 18:43
@onlyjob do you follow the podman issue? For now there is no way to use the http API to get it working. What is your opinion?

**Comment by onlyjob** [comment] 2021-01-15 19:35
Yes, I'm following, thanks... Not upgrading is my only option, obviously... :(  But that also means that we can't disable deprecated Varlink in Debian's Podman...

**Comment by pablofsf** [comment] 2021-05-04 14:54
@onlyjob, this has in principle been fixed in #101. There is a simple test which worked successfully and imports the right images from the archives. However, I did not do any real-world testing. If you are able to check it out, maybe there is a chance any further bugs appear or we can consider this as solved. Only `oci-archive` and `docker-archive` are currently allowed transports other than the default `docker`

**Closed** 2022-01-03 19:56 UTC
