### ISSUE TITLE
sometimes fails to start: Reattachment process not found

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad-driver-podman#12] opened 2019-12-20 08:40 UTC
```
dispensing initial plugin failed: driver=podman error="failed to start plugin: Reattachment process not found"
```

This is happening on restart of _nomad_ probably when some allocations are still running when the _nomad_ is stopped...

**Comment by onlyjob** [comment] 2019-12-20 09:01
It may have something to do with `client/state.db` which I had to remove to remedy this situation.

Basically driver is not "sometimes" fail. It just could not be started any more until I removed `state.db`...

**Comment by towe75** [comment] 2019-12-20 10:45
@onlyjob yes, i know about this problem and have it sometimes when working on the driver. 

Also nomad-driver-lxc shows same behavior so i assume that it might be a bug in the nomad plugin subsystem. Possibly they keep some socket path in this state.db. Upon starting nomad it seems they try to reuse the old socket. The socket might have been gone because of a reboot or some another side effect. Also reusing the socket makes IMHO not much sense because nomad itself forks the plugin as a sub process and so it can easily create/use a new socket-file each time.

For now i did not have the time to investigate or raise a bug but i can confirm that removing client/state.db helps.

**Comment by onlyjob** [comment] 2019-12-20 11:24
Interesting, thanks. Nomad [had a serious problem with `state.db` in the past](https://github.com/hashicorp/nomad/issues/2560) and it looks like not all the problems were fixed...

I wonder if adding `After=io.podman.service` on _nomad.service_ could be of help?
I just had to add it due to Nomad timeout on shutdown...

**Comment by towe75** [comment] 2019-12-20 11:42
Well, startup ordering is always a good idea. A systemd unit dropin can handle this without tainting podman or nomad units.

But the bug itself is IMHO not directly related. It does not even try to start the plugin in this case. Having podman not running yet would yield a different result, the plugin would load but deactivate itself. 

One of my next commits will, btw, include a limited retry on every varlink call which failed due to a socket io problem. So it would tolerate a small service startup glitch as well. Also restarting the podman socket will then no longer be a problem.

**Comment by schmichael** [comment] 2020-01-10 20:18
My best guess is that the error is being reported here: https://github.com/hashicorp/nomad/blob/v0.10.2/client/pluginmanager/drivermanager/instance.go#L205

And the error [`ErrProcessNotFound`](https://pkg.go.dev/github.com/hashicorp/go-plugin?tab=doc#pkg-variables) is being returned because `go-plugin` was told to reattach to a process that does not exist (probably [here](https://github.com/hashicorp/go-plugin/blob/809113480b559c989ea9cfcff62e9d387961f60b/client.go#L797-L805)).

Unfortunately a lot of context and lower level errors is missing from the error output, so it's hard to know for sure.

Is it possible the plugin process exited while the Nomad agent was down, and Nomad is failing to start a new plugin process? Nomad should restart a plugin if its unable to reattach to handle server reboot cases.

Please [open an issue on Nomad's side](https://github.com/hashicorp/nomad/issues/new) if you think that's the case. Throwing some additional debugging logging into [plugin loading](https://github.com/hashicorp/nomad/blob/v0.10.2/helper/pluginutils/loader/loader.go#L192-L259) may help narrow down the issue.

**Comment by towe75** [comment] 2020-01-11 11:33
I will try to get some reproducible case or at least more details before i open a issue for this bug. For now it happens rather randomly. 
Thx for checking.

**Comment by towe75** [comment] 2021-03-10 18:56
@onlyjob i did not came across this problem for quite some time and i assume it was resolved with some nomad release. Ok to close?

**Comment by jrasell** [comment] 2021-06-18 08:57
I am going to close out this issue. If you are still encountering the problem, please feel free to reopen this issue, or open a new issue linking to this.

**Closed by jrasell** 2021-06-18 08:57 UTC

**Comment by suikast42** [comment] 2023-04-15 00:18
Have a issue with the same error in the logging. Maybe https://github.com/hashicorp/nomad/issues/16893 related to this
